
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int A_CHAVE = 34;
  public static final int F_CHAVE = 35;
  public static final int MENORQ = 25;
  public static final int A_PAREN = 36;
  public static final int F_PAREN = 37;
  public static final int DIFERENTE = 23;
  public static final int INT = 10;
  public static final int VIRGULA = 42;
  public static final int PONTO = 41;
  public static final int NEGACAO = 33;
  public static final int E = 26;
  public static final int STATIC = 4;
  public static final int IGUAL = 22;
  public static final int OU = 27;
  public static final int A_COLC = 38;
  public static final int CLASS = 2;
  public static final int MAIS = 28;
  public static final int DIV = 31;
  public static final int NUM = 43;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 18;
  public static final int ID = 44;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 9;
  public static final int PONTO_VIRGULA = 40;
  public static final int TRUE = 16;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MENOS = 29;
  public static final int MOD = 32;
  public static final int VOID = 5;
  public static final int ATRIB = 21;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 8;
  public static final int STRING = 7;
  public static final int TEXTO = 45;
  public static final int MENOR_IGUAL = 24;
  public static final int FALSE = 17;
  public static final int F_COLC = 39;
  public static final int VEZES = 30;
  public static final int PRINT = 15;
  public static final int LENGTH = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "EXTENDS",
  "RETURN",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "PRINT",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "LENGTH",
  "ATRIB",
  "IGUAL",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MENORQ",
  "E",
  "OU",
  "MAIS",
  "MENOS",
  "VEZES",
  "DIV",
  "MOD",
  "NEGACAO",
  "A_CHAVE",
  "F_CHAVE",
  "A_PAREN",
  "F_PAREN",
  "A_COLC",
  "F_COLC",
  "PONTO_VIRGULA",
  "PONTO",
  "VIRGULA",
  "NUM",
  "ID",
  "TEXTO"
  };
}

